matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.2
install:
  - npm install
  - npm run build
language: node_js
node_js:
  - 7.10.0
  - 8.0.0
  - 9.2.0